# --- Application & Server ---
server.error.include-message=always
server.error.include-stacktrace=on_param

# --- URLs (Local) ---
app.frontend-url=http://app.localhost:5173
app.gestao-url=http://gestao.localhost:5173
app.api-url=http://localhost:8080
app.logo-url=https://api.icarplus.com.br/uploads/static/logo-icar-email.png

# --- Database (Local) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/icar_platforms
spring.datasource.username=felipe
spring.datasource.password=Dev10fs2022@IcarSystem
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA & Hibernate (Local) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

# --- File Storage (Local) ---
storage.location=uploads
storage.base-url=http://localhost:8080

# --- Email (Local) ---
spring.mail.password=Dev10fs2022@IcarSystem

# --- Mercado Pago (Local) ---
mercadopago.redirect-uri=https://075454c58dc3.ngrok-free.app/api/v1/mercado-pago/callback
mercadopago.app-id=SEU_APP_ID_SANDBOX_AQUI
mercadopago.client-secret=SEU_CLIENT_SECRET_SANDBOX_AQUI
mercadopago.webhook-secret-key=SEU_WEBHOOK_SECRET_SANDBOX_AQUI

# --- Logging (Local) ---
logging.level.com.icar=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %-5level [%thread] %logger{36} - %msg%n
