# --- application-dev.properties ---

# --- URLs (Local) ---
app.frontend-url=http://app.localhost:5173
app.gestao-url=http://gestao.localhost:5173
app.api-url=http://localhost:8080
app.logo-url=https://api.icarplus.com.br/uploads/static/logo-icar-email.png

# --- Database (Local) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/icar_platforms
spring.datasource.username=felipe
spring.datasource.password=Dev10fs2022@IcarSystem
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA & Hibernate (Local) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# --- File Storage (Local) ---
storage.location=uploads
storage.base-url=http://localhost:8080

# --- Email (Local) ---
spring.mail.password=Dev10fs2022@IcarSystem

# --- Mercado Pago (Desenvolvimento / Teste) ---
mercadopago.redirect-uri=https://075454c58dc3.ngrok-free.app/api/v1/mercado-pago/callback
mercadopago.app-id=7605812219806027
mercadopago.client-secret=5rM0yZq484dFiSWiN76JLNnDvN3QVAic
mercadopago.webhook-secret-key=cf9aa2cc596796abbc6e1433a4b3be744ed4f8e02fff501c428ac18a01295a2a

# --- Logging (Local) ---
logging.level.com.icar=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %-5level [%thread] %logger{36} - %msg%n
